### ISSUE TITLE
Fix Ranking for Anytime Contest

### ISSUE THREAD

**Issue by sandy2008** [sokoide-developers/OnlineJudge#3]
- Minus a startTime for each submission.
- <img width="1177" alt="截屏2020-06-10 12 26 04" src="https://user-images.githubusercontent.com/18073670/84223700-8eff9980-ab15-11ea-8bdd-a52757e55714.png">

**Comment by sandy2008** [comment]
@sokoide 
Hi So-san, the code is in this line
https://github.com/sokoide-developers/OnlineJudge/blob/sokoide-dev/judge/dispatcher.py#L368

**Comment by sokoide** [comment]
Moved to OnlineJudge (Django) because the problem was there.
Fixed by commit d00435780910495d94ed6dda71c2cb6b98659a8a in sokoide-dev branch.
